import type { Event, Artist, MediaItem, Partner, PressAsset } from './types';

export const DEMO_EVENTS: Event[] = [
  {
    id: '1',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'KINTESSENS LIVE — Saison I, Édition 1',
    slug: 'kintessens-live-saison-1-edition-1',
    type: 'live',
    status: 'past',
    content_status: 'published',
    date: '2026-03-15',
    time: '20:00',
    location: 'Institut Français de Dakar',
    city: 'Dakar',
    country: 'Sénégal',
    description_short: 'La première édition de KINTESSENS LIVE — une soirée de performances immersives mêlant musique live, poésie et arts visuels au cœur de Dakar.',
    description_long: `La scène s'allume. Les lumières se fondent dans l'obscurité. Et KINTESSENS LIVE fait son entrée dans l'histoire culturelle de Dakar.\n\nCette première édition a réuni des artistes d'exception dans un cadre unique : l'Institut Français de Dakar, transformé pour l'occasion en espace d'expérience totale. Musique live, performances poétiques, projections visuelles et captation haut de gamme — KINTESSENS redéfinit ce que signifie vivre la création contemporaine africaine.`,
    cover_image: '/images/hero/main.jpg',
    gallery: ['/images/hero/main.jpg'],
    video_teaser: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    lineup: ['Somi', 'Awa Ly', 'Blick Bassy'],
    featured: true,
    flagship: true,
    meta_title: 'KINTESSENS LIVE — Saison I, Édition 1',
    meta_description: 'La première édition de KINTESSENS LIVE à Dakar — performances immersives, musique live, poésie et arts visuels.',
  },
  {
    id: '2',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'KINTESSENS FESTIVAL 2026',
    slug: 'kintessens-festival-2026',
    type: 'festival',
    status: 'upcoming',
    content_status: 'published',
    date: '2026-11-28',
    time: '16:00',
    location: 'Grand Théâtre National',
    city: 'Dakar',
    country: 'Sénégal',
    description_short: 'Le festival annuel KINTESSENS — trois jours de programmation multidisciplinaire au cœur de Dakar, avec des artistes africains et internationaux.',
    description_long: `KINTESSENS FESTIVAL est le moment culminant de la saison artistique. Trois jours d'expériences inédites, de rencontres, d'émotions et de création au plus haut niveau.\n\nProgrammation multidisciplinaire, scénographies immersives, artistes du continent et de la diaspora, tables rondes, ateliers — le festival est bien plus qu'un événement. C'est une célébration de la quintessence de la création contemporaine africaine.`,
    cover_image: '/images/events/festival-1.jpg',
    gallery: ['/images/events/festival-1.jpg'],
    video_teaser: undefined,
    lineup: ['Fatoumata Diawara', 'Baloji', 'Asa', 'Nneka', 'Les Amazones d\'Afrique'],
    featured: true,
    flagship: true,
    cta_label: 'Réserver ma place',
    cta_url: '#billetterie',
    meta_title: 'KINTESSENS FESTIVAL 2026 — Dakar',
    meta_description: '3 jours de programmation multidisciplinaire au Grand Théâtre National de Dakar.',
  },
  {
    id: '3',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'KINTESSENS SOLIDARITY — Abidjan Session',
    slug: 'kintessens-solidarity-abidjan',
    type: 'solidarity',
    status: 'upcoming',
    content_status: 'published',
    date: '2026-09-20',
    time: '18:00',
    location: 'Centre Culturel de l\'INSAAC',
    city: 'Abidjan',
    country: 'Côte d\'Ivoire',
    description_short: 'Une session SOLIDARITY portée par l\'engagement : concerts, ateliers créatifs et actions culturelles au service des jeunes artistes d\'Abidjan.',
    description_long: `KINTESSENS SOLIDARITY incarne le volet sociétal de la marque. À Abidjan, nous invitons la communauté à vivre un moment de création partagée, de transmission et de solidarité artistique.\n\nAteliers créatifs, performances spontanées, mentorat — une journée entière au service de la jeune création ivoirienne.`,
    cover_image: '/images/events/solidarity-1.jpg',
    gallery: [],
    featured: false,
    flagship: false,
    cta_label: 'Participer',
    cta_url: '/contact',
    meta_title: 'KINTESSENS SOLIDARITY — Abidjan',
    meta_description: 'Session solidaire à Abidjan — concerts, ateliers et actions culturelles pour les jeunes artistes.',
  },
  {
    id: '4',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'KINTESSENS LIVE — Saison I, Édition 2',
    slug: 'kintessens-live-saison-1-edition-2',
    type: 'live',
    status: 'upcoming',
    content_status: 'published',
    date: '2026-06-07',
    time: '21:00',
    location: 'Palais de la Musique',
    city: 'Abidjan',
    country: 'Côte d\'Ivoire',
    description_short: 'La deuxième édition de KINTESSENS LIVE s\'installe à Abidjan pour une nuit de performances live haut de gamme.',
    description_long: `Après le succès de Dakar, KINTESSENS LIVE traverse la frontière et s\'installe à Abidjan. Même ambition, même exigence artistique, nouvelle énergie.\n\nUne nuit d\'exception au Palais de la Musique — captation cinématographique, acoustique irréprochable, artistes au sommet de leur art.`,
    cover_image: '/images/events/live-2.jpg',
    gallery: [],
    lineup: ['Awa Ly', 'Amadou Diallo', 'Ines Makboul'],
    featured: true,
    flagship: false,
    cta_label: 'Réserver',
    cta_url: '#billetterie',
    meta_title: 'KINTESSENS LIVE — Édition 2 à Abidjan',
    meta_description: 'KINTESSENS LIVE s\'installe à Abidjan pour une nuit de performances live haut de gamme.',
  },
];

export const DEMO_ARTISTS: Artist[] = [
  {
    id: '1',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Amara Diallo',
    slug: 'amara-diallo',
    category: 'music',
    status: 'resident',
    content_status: 'published',
    photo: '/images/artists/dakar-live.jpg',
    bio_short: 'Musicien compositeur entre Dakar et Paris, Amara Diallo tisse des ponts entre tradition mandingue et jazz contemporain.',
    bio_long: `Né à Dakar et formé entre le Conservatoire National de Paris et les rues de Médina, Amara Diallo est l'un des artistes les plus singuliers de sa génération.\n\nSa musique est un voyage — entre kora et contrebasse, entre tradition mandingue et jazz contemporain, entre Dakar et le monde. Artiste résident KINTESSENS depuis la première saison, il incarne la quintessence de ce que la marque défend : l'excellence, le dialogue et la création au plus haut niveau.`,
    city: 'Paris / Dakar',
    country: 'Sénégal',
    instagram: '@amaradiallo',
    spotify: 'amaradiallo',
    event_ids: ['1', '2'],
    featured: true,
    meta_title: 'Amara Diallo — Musicien KINTESSENS',
    meta_description: 'Découvrez Amara Diallo, musicien résident KINTESSENS entre tradition mandingue et jazz contemporain.',
  },
  {
    id: '2',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Zahira Mbaye',
    slug: 'zahira-mbaye',
    category: 'poetry',
    status: 'guest',
    content_status: 'published',
    photo: '/images/artists/artist-2.jpg',
    bio_short: 'Poète et performeuse sénégalaise, Zahira Mbaye porte une voix puissante sur les questions d\'identité, de mémoire et de liberté.',
    bio_long: `Zahira Mbaye est une voix qui traverse les frontières. Sa poésie, viscérale et lyrique, mêle wolof, français et images pour raconter l'Afrique d'aujourd'hui.\n\nSes performances scéniques sont des expériences totales — le verbe comme corps, la parole comme acte politique et artistique.`,
    city: 'Dakar',
    country: 'Sénégal',
    instagram: '@zahirambaye',
    event_ids: ['1'],
    featured: true,
    meta_title: 'Zahira Mbaye — Poète KINTESSENS',
    meta_description: 'Zahira Mbaye, poète et performeuse sénégalaise invitée KINTESSENS.',
  },
  {
    id: '3',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Kofi Asante',
    slug: 'kofi-asante',
    category: 'visual_arts',
    status: 'artistic_council',
    content_status: 'published',
    photo: '/images/artists/artist-3.jpg',
    bio_short: 'Plasticien et directeur artistique ghanéen, membre du Conseil Artistique KINTESSENS. Son œuvre interroge les représentations de l\'Afrique contemporaine.',
    bio_long: `Kofi Asante est l'un des plasticiens africains les plus exposés de sa génération. Entre peinture, installation et direction artistique, son travail explore les imaginaires africains en mutation.\n\nMembre fondateur du Conseil Artistique KINTESSENS, il contribue à définir l'esthétique et les valeurs de la marque.`,
    city: 'Accra / Londres',
    country: 'Ghana',
    website: 'https://kofiasante.art',
    event_ids: ['2'],
    featured: true,
    meta_title: 'Kofi Asante — Plasticien, Conseil Artistique KINTESSENS',
    meta_description: 'Kofi Asante, plasticien ghanéen et membre du Conseil Artistique KINTESSENS.',
  },
  {
    id: '4',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Ines Makboul',
    slug: 'ines-makboul',
    category: 'performance',
    status: 'guest',
    content_status: 'published',
    photo: '/images/artists/artist-4.jpg',
    bio_short: 'Danseuse et chorégraphe franco-marocaine, Ines Makboul explore la transmission du corps et de la mémoire collective dans ses performances.',
    bio_long: `Formée à l'École des Arts de Casablanca et au Centre National de la Danse de Paris, Ines Makboul développe une pratique chorégraphique nourrie de tradition et d'expérimentation.\n\nSes pièces sont des dialogues entre les corps, les générations et les cultures méditerranéennes.`,
    city: 'Casablanca / Paris',
    country: 'Maroc',
    instagram: '@inesmakboul',
    event_ids: ['4'],
    featured: false,
    meta_title: 'Ines Makboul — Danseuse et Chorégraphe KINTESSENS',
    meta_description: 'Ines Makboul, chorégraphe franco-marocaine invitée KINTESSENS.',
  },
  {
    id: '5',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Djibril Touré',
    slug: 'djibril-toure',
    category: 'audiovisual',
    status: 'resident',
    content_status: 'published',
    photo: '/images/artists/artist-5.jpg',
    bio_short: 'Réalisateur et directeur de la photographie guinéen, Djibril Touré capte l\'âme de la création africaine avec une signature visuelle puissante.',
    bio_long: `Djibril Touré est l'œil de KINTESSENS. Réalisateur, directeur de la photographie et artiste visuel, il développe depuis 10 ans un langage cinématographique profondément ancré dans les esthétiques africaines.\n\nArtiste résident, il est en charge de la captation artistique de toutes les sessions KINTESSENS LIVE.`,
    city: 'Conakry / Dakar',
    country: 'Guinée',
    instagram: '@djibriltoure',
    youtube: 'djibriltoure',
    event_ids: ['1', '2', '4'],
    featured: true,
    meta_title: 'Djibril Touré — Réalisateur KINTESSENS',
    meta_description: 'Djibril Touré, réalisateur résident KINTESSENS et directeur de la photographie.',
  },
  {
    id: '6',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Nadia Essomba',
    slug: 'nadia-essomba',
    category: 'music',
    status: 'emerging',
    content_status: 'published',
    photo: '/images/artists/artist-6.jpg',
    bio_short: 'Chanteuse et auteure-compositrice camerounaise, Nadia Essomba mêle afrobeats, soul et influences classiques dans un style inimitable.',
    bio_long: `Nadia Essomba est une des voix les plus prometteuses de la jeune scène africaine. Elle compose, chante et performe avec une maturité impressionnante pour son âge.\n\nDécouverte lors d\'une session KINTESSENS SOLIDARITY à Yaoundé, elle rejoint maintenant la programmation principale comme artiste émergente à suivre absolument.`,
    city: 'Yaoundé / Paris',
    country: 'Cameroun',
    instagram: '@nadiaessomba',
    spotify: 'nadiaessomba',
    event_ids: ['3'],
    featured: false,
    meta_title: 'Nadia Essomba — Chanteuse KINTESSENS',
    meta_description: 'Nadia Essomba, artiste émergente camerounaise découverte par KINTESSENS.',
  },
  {
    id: '7',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Léa Touré',
    slug: 'lea-toure',
    category: 'visual_arts',
    status: 'emerging',
    content_status: 'published',
    photo: '/images/artists/artist-7.jpg',
    bio_short: 'Artiste plasticienne ivoirienne travaillant autour des matières organiques et des récits de la mémoire africaine.',
    bio_long: `Léa Touré travaille avec la terre, le tissu, le bois et les pigments naturels pour créer des œuvres qui parlent de mémoire, de territoire et d\'identité.\n\nSes installations ont été exposées à Abidjan, Lagos et Paris.`,
    city: 'Abidjan',
    country: 'Côte d\'Ivoire',
    instagram: '@leatoure_art',
    event_ids: ['2'],
    featured: false,
    meta_title: 'Léa Touré — Artiste plasticienne KINTESSENS',
    meta_description: 'Léa Touré, plasticienne ivoirienne et artiste émergente KINTESSENS.',
  },
  {
    id: '8',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Marcus Eze',
    slug: 'marcus-eze',
    category: 'music',
    status: 'guest',
    content_status: 'published',
    photo: '/images/artists/artist-8.jpg',
    bio_short: 'Producteur et musicien nigérian, Marcus Eze est l\'un des architectes sonores les plus recherchés de la scène afrobeats internationale.',
    bio_long: `Marcus Eze a collaboré avec les plus grands noms de la scène africaine et internationale. Son studio est un lieu de rencontre entre les sons du continent et les courants globaux.\n\nInvité d\'honneur du KINTESSENS FESTIVAL 2026, il présentera pour la première fois en live ses compositions orchestrales.`,
    city: 'Lagos / Barcelone',
    country: 'Nigéria',
    instagram: '@marcuseze',
    youtube: 'marcusezemusic',
    event_ids: ['2'],
    featured: true,
    meta_title: 'Marcus Eze — Producteur et Musicien KINTESSENS',
    meta_description: 'Marcus Eze, producteur nigérian invité d\'honneur du KINTESSENS FESTIVAL 2026.',
  },
];

export const DEMO_MEDIA: MediaItem[] = [
  {
    id: '1',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'KINTESSENS LIVE — Saison I, Teaser officiel',
    slug: 'kintessens-live-saison-1-teaser',
    type: 'short_clip',
    content_status: 'published',
    thumbnail: '/images/media/media-1.jpg',
    video_source: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Le teaser officiel de la première saison KINTESSENS LIVE — une invitation à l\'expérience.',
    tags: ['teaser', 'live', 'saison-1'],
    artist_id: '1',
    event_id: '1',
    featured: true,
  },
  {
    id: '2',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Amara Diallo — Session acoustique',
    slug: 'amara-diallo-session-acoustique',
    type: 'video_live',
    content_status: 'published',
    thumbnail: '/images/media/media-2.jpg',
    video_source: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Une session acoustique intime avec Amara Diallo, enregistrée dans les studios KINTESSENS à Dakar.',
    tags: ['acoustique', 'session', 'musique'],
    artist_id: '1',
    featured: true,
  },
  {
    id: '3',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Coulisses — Édition 1 LIVE',
    slug: 'coulisses-edition-1-live',
    type: 'backstage',
    content_status: 'published',
    thumbnail: '/images/media/media-3.jpg',
    video_source: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Dans les coulisses de la première édition KINTESSENS LIVE — préparations, émotions et moments rares.',
    tags: ['backstage', 'coulisses', 'edition-1'],
    event_id: '1',
    featured: false,
  },
  {
    id: '4',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Zahira Mbaye — Performance poétique',
    slug: 'zahira-mbaye-performance-poetique',
    type: 'video_live',
    content_status: 'published',
    thumbnail: '/images/media/media-4.jpg',
    video_source: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'La performance poétique de Zahira Mbaye captée lors de la nuit d\'ouverture — un moment de grâce absolu.',
    tags: ['poésie', 'performance', 'live'],
    artist_id: '2',
    event_id: '1',
    featured: true,
  },
  {
    id: '5',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'KINTESSENS — Le documentaire (extrait)',
    slug: 'kintessens-documentaire-extrait',
    type: 'documentary',
    content_status: 'published',
    thumbnail: '/images/media/media-5.jpg',
    video_source: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Extrait du documentaire sur la naissance de KINTESSENS — la vision des fondateurs et l\'aventure d\'une marque culturelle.',
    tags: ['documentaire', 'histoire', 'vision'],
    featured: false,
  },
  {
    id: '6',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Kofi Asante — Entretien exclusif',
    slug: 'kofi-asante-entretien',
    type: 'interview',
    content_status: 'published',
    thumbnail: '/images/media/media-6.jpg',
    video_source: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Kofi Asante, directeur artistique du Conseil KINTESSENS, livre une réflexion sur l\'art contemporain africain et le rôle de la marque.',
    tags: ['interview', 'conseil-artistique', 'arts-visuels'],
    artist_id: '3',
    featured: false,
  },
];

export const DEMO_PARTNERS: Partner[] = [
  {
    id: '1',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Orange Sénégal',
    slug: 'orange-senegal',
    type: 'sponsor',
    level: 'platinum',
    logo: '/images/partners/orange.png',
    description: 'Sponsor principal de KINTESSENS, Orange Sénégal accompagne le développement culturel africain.',
    website: 'https://sonatel.com',
    featured: true,
    homepage: true,
  },
  {
    id: '2',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Institut Français',
    slug: 'institut-francais',
    type: 'institution',
    level: 'institutional',
    logo: '/images/partners/if.png',
    description: 'Partenaire institutionnel de longue date, l\'Institut Français soutient les échanges culturels franco-africains.',
    website: 'https://www.institutfrancais.com',
    featured: true,
    homepage: true,
  },
  {
    id: '3',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Jeune Afrique',
    slug: 'jeune-afrique',
    type: 'media',
    level: 'gold',
    logo: '/images/partners/ja.png',
    description: 'Partenaire média principal de KINTESSENS, Jeune Afrique assure la couverture éditoriale des événements.',
    website: 'https://www.jeuneafrique.com',
    featured: true,
    homepage: true,
  },
  {
    id: '4',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    name: 'Canal+',
    slug: 'canal-plus',
    type: 'media',
    level: 'gold',
    logo: '/images/partners/canal.png',
    description: 'Canal+ diffuse les captations live KINTESSENS et accompagne la production audiovisuelle de la marque.',
    website: 'https://www.canalplus.com',
    featured: true,
    homepage: true,
  },
];

export const DEMO_PRESS: PressAsset[] = [
  {
    id: '1',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Dossier de presse KINTESSENS 2026',
    type: 'dossier',
    file_url: '/press/dossier-presse-kintessens-2026.pdf',
    description: 'Dossier de presse complet — présentation de la marque, formats, éditions et perspectives.',
    public_access: true,
  },
  {
    id: '2',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Communiqué — Lancement KINTESSENS LIVE Saison II',
    type: 'communique',
    file_url: '/press/communique-live-saison-1.pdf',
    description: 'Communiqué officiel annonçant le lancement de la première saison KINTESSENS LIVE.',
    public_access: true,
  },
  {
    id: '3',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Pack logos KINTESSENS (HD)',
    type: 'logo',
    file_url: '/press/logos-kintessens-hd.zip',
    description: 'Tous les logos KINTESSENS en haute définition — formats PNG, SVG, PDF.',
    public_access: true,
  },
  {
    id: '4',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    title: 'Photos officielles — Édition 1',
    type: 'photo_hd',
    file_url: '/press/photos-edition-1.zip',
    description: 'Sélection de photos haute définition de la première édition KINTESSENS LIVE à Dakar.',
    public_access: true,
  },
];

// KPIs for demo dashboard
export const DEMO_KPIS = {
  visits: 12847,
  events_published: 4,
  artists_published: 8,
  media_published: 6,
  messages: 23,
  partners_active: 4,
  newsletter_subscribers: 1284,
  contact_requests: 23,
};
